matze/wastebin

Dockerfile

Update the Rust toolchain version in the Dockerfile.
Tested the change on an x86 VM, the build succeeds.
Closes #31

build: update to Rust 1.70

---

README.md

I like it when selfhostable services have a small docker-compose example. Even with the docker example it's one step more to get it running if you use compose (what most people probably do when selfhosting).

add simple docker-compose example to readme

---

README.md

As suggested in #45 I added a comment on nix to the readme. Didn't go into much detail, but should be more than enough for Nixos users to know how to use it. I'm also working on adding it as an official nixos package over on https://github.com/NixOS/nixpkgs/pull/287455

Add nix to readme

---

.github/workflows/rust.yml
src/env.rs
src/highlight.rs
src/id.rs
src/main.rs
src/pages.rs
src/routes/assets.rs
src/routes/form.rs
src/routes/json.rs
src/routes/mod.rs
src/routes/paste.rs
src/test_helpers.rs
templates/base.html
templates/burn.html
templates/error.html
templates/index.html
templates/paste.html

Hi there! 👋
I took a shot at letting `wastebin` work when served from a sub-path (e.g. https://example.com/wastsebin/). It's a WIP, but I thought of getting this out early and discuss 1. if useful; 2. improvements.
The idea is to re-use the `WASTEBIN_BASE_URL` variable and get its `path` component (if any).
Right now:
What's the best approach to add the test? Duplicate them? Run them in a `for` loop with / without the sub-path?
Also, I am not convinced of storing the base path in the `metadata` as a static variable. Are there other approaches?

Handle serving from a sub-path

---

.gitignore
src/themes/style.css
templates/index.html

A scrollbar was getting introduced due to the size of the langs list. This reduces the size from 23 options to 17 options, and also adjusts some height attributes in other elements to remove the scrollbar completely.

Reduce lang list size to fix overflow

---

README.md
src/env.rs
src/main.rs
src/pages.rs
src/routes/form.rs
src/routes/json.rs
src/test_helpers.rs
templates/index.html

This aims to implement #54, and also be an improvement over #55.
Changes Made:
- Add ~`WASTEBIN_MAX_PASTE_EXPIRY`~ `WASTEBIN_MAX_PASTE_EXPIRATION`
- Ensure both the form and json routes honor the set limit (if any) (currently not done by #55)
- ~Currently it simply clamps the expiry time~
- Invalid values or too large values will cause an error
- Remove invalid options from the new-paste UI
- Correctly hide `never expire` if any limit is set
- Always show `burn`, even if the limit is 0
- Default select the "top" most expiry (either "never", or 10 minutes)

Add maximum expiry

---

Dockerfile.arm
README.md

Aims to address https://github.com/matze/wastebin/issues/29.

Adding option to build ARM based image

---

src/themes/style.css
templates/base.html
templates/index.html

This gets rid of unwanted vertical scrollbar on the home page.

Improve main container CSS

---

Cargo.toml

In particular checks about panic and stdout usage, and value truncation.

More strict clippy lints

---

CHANGELOG.md
README.md
src/db.rs
src/env.rs
src/main.rs
src/pages.rs
src/routes/form.rs
src/routes/json.rs

Make clear to readers that the value 0 is not supported and has no special meaning.
Also allows the compiler to improve enum layouts.

Make use of NonZero

---

src/pages.rs
src/routes/mod.rs
src/routes/paste.rs
templates/burn.html

Since one can not visit the actual page (without deleting it) for one-time-pastes, there is no other way to get the QR code for URL of the created paste.

Show QR code after a burn paste has been created

---

Cargo.lock
Cargo.toml
src/crypto.rs
src/errors.rs
src/pages.rs
src/routes/assets.rs
src/routes/form.rs
src/routes/mod.rs
src/routes/paste.rs
src/themes/ayu-dark.tmTheme
src/themes/ayu-light.tmTheme
src/themes/style.css
templates/base.html
templates/formatted.html
templates/index.html
templates/paste.html

See individual commits for more details.

Miscellaneous tweaks

---

Dockerfile

Bump Rust version due to
```
4.718 error: rustc 1.80.1 is not supported by the following package:                                                                                                                         
4.718   wastebin@2.5.0 requires rustc 1.83     
```

Update Dockerfile to use Rust 1.83

---

src/themes/style.css

Avoid additional erroneous newlines being present when copying the paste content either via mouse selection or Ctrl+a.
No newlines are copied by chromium, firefox still inserts a prefix newline.
Fixes: #72

Improve paste selection

---

src/themes/style.css
templates/base.html
templates/index.html
templates/paste.html

Reported by https://validator.w3.org/nu/:
The element button must not appear as a descendant of the a element.
Split from #80.

Drop <button> under <a>

---

Dockerfile.arm

Currently, the build fails on ARM with the error `wastebin@2.5.0 requires rustc 1.83` as the ARM dockerfile is not up-to-date with the main Dockerfile. This PR simply bumps the version to fix that, matching commit bf31627.

Bump `Dockerfile.arm`'s rust to 1.83

---

src/themes/style.css

Especially on phones the size of the padding is significant. This patch removes padding around the paste content if the screen is small.

Remove padding for small screens

---

Cargo.toml

Specifying dependencies as `= "0"` is almost exactly like "specifying" `= "*"` for crates >= 1.x. I realize there is a lockfile, but it still seems reckless.

Lock 0.x dependencies to semver-compatible versions

---

src/env.rs
src/highlight.rs
src/javascript/index.js
src/javascript/paste.js
src/main.rs
src/routes/assets.rs
src/themes/style.css
templates/base.html
templates/encrypted.html
templates/index.html
templates/paste.html

Modern browser support security headers, in particular Content Security
Policy (CSP)(https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
These can help mitigating XSS vulnerabilities, in the case of pastes by
disallowing inline styles and scripts.
Move all current inline styles into the global style.css, and refactor
all inline javascript into separate asset files.

Security headers

---

src/db.rs
src/migrations/0007-add-title-column.sql
src/pages.rs
src/routes/form.rs
src/routes/json.rs
src/routes/mod.rs
src/routes/paste.rs
src/themes/style.css
templates/base.html
templates/index.html
templates/paste.html

Fixes #90 
Try a live version here https://paste.fliegendewurst.eu/dPmU6a.log

Allow setting paste title

---

src/themes/style.css
templates/base.html

If the title is one very long word the QR code button is moved past the screen width. Fix by making that button group properly sized.
See e.g. https://bin.bloerg.net/pOjqAb

Fix QR code button overflowing past the screen

---

README.md

https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313
Meant to fix this yesterday too. But i forgot. 
So here is another PR to fix a small thing. It will still run with it, just with a warning. So no reason for it to be there amymore.

Versioning is obsolete

---

flake.nix

There are two ways to specify the dependencies of a Nix-packaged Rust application: cargoHash and cargoLock. The latter reads dependencies from Cargo.lock directly, the first needs to be updated on every change to Cargo.lock.

flake.nix: use Cargo.lock directly

---

Cargo.toml

Optimize the argon crate even in debug builds, such that encryption and decryption are not tremendously slow.

Optimize crypto in debug builds

---

crates/wastebin_core/Cargo.toml

Building only the ctl crate currently fails via:
error[E0432]: unresolved import `tokio::task::spawn_blocking`
--> crates/wastebin_core/src/crypto.rs:5:5
|
5   | use tokio::task::spawn_blocking;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `spawn_blocking` in `task`
|
note: found an item that was configured out
--> /home/christian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.1/src/task/mod.rs:273:23
|
273 |     pub use blocking::spawn_blocking;
|                       ^^^^^^^^^^^^^^
note: the item is gated behind the `rt` feature
--> /home/christian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.1/src/task/mod.rs:269:1
|
269 | / cfg_rt! {
270 | |     pub use crate::runtime::task::{JoinError, JoinHandle};
271 | |
272 | |     mod blocking;
...   |
323 | | }
| |_^ …

Fix building ctl crate

---

crates/wastebin_server/templates/index.html

See https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values

Drop unnecessary html element closing slash

---

README.md

close #150 
We provide the POST api endpoint at `/` but the document is still suggesting POST to `/api`

docs(readme): fix outdated example commands

---

crates/wastebin_server/templates/index.html

Explicitly disable auto-capitalization, whose default depends on the browser.
Require input to avoid (accidental) empty pastes.

Update textarea properties

---

.github/workflows/release.yml

Fix current CI action, and introduce support for macos/linux/windows - arm64/x86_64 builds (and linux-riscv-glibc)

ci: fix ci & support more platforms

---

CHANGELOG.md
Cargo.lock
crates/wastebin_core/Cargo.toml
crates/wastebin_core/src/db.rs
crates/wastebin_ctl/Cargo.toml
crates/wastebin_ctl/src/main.rs
crates/wastebin_server/Cargo.toml
crates/wastebin_server/src/main.rs
crates/wastebin_server/src/test_helpers.rs

Use a dedicated database handler thread that reads database commands from a kanal channel and return results on a oneshot channel. On an aging Ryzen 7 3700X, this improves throughput from 28k to 43k requests per seconds as measured using the https://github.com/mokurin000/wastebin-bench tool.

Improve performance by not locking the database

---

CHANGELOG.md
crates/wastebin_server/src/assets.rs

Set `color-scheme: dark` for dark theme
